export default {
  EMAIL_ALREADY_EXISTS: 1,
  USERNAME_ALREADY_EXISTS: 2,
  EMAIL_NOT_EXISTING: 3,
  EMAIL_NOT_PROVIDED: 4,
  SINUP_MISSING_TOKEN: 5,
  SIGNUP_INVALID_TOKEN: 6,
  REFRESH_TOKEN_NOT_FOUND: 7,
  REFRESH_TOKEN_INVALID: 8,
  USERNAME_NOT_EXISTING: 9,
}